# -*- coding: utf-8 -*-
"""Corn-leaf-diassess-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wzhbp5FyyG0lh1uMSvZtkjVWqNbepMuM
"""

# ==========================================
# 1. SETUP & DATASET DOWNLOAD
# ==========================================
!pip install -q kagglehub
import kagglehub
import os

print("Downloading dataset via kagglehub...")
# Download latest version of the dataset
dataset_path = kagglehub.dataset_download("yasirahmad0810/consolidated-corn-dataset")
print("Path to dataset files:", dataset_path)

# Point the training directory to the downloaded path
# We check if there's a nested 'data' folder just in case
DATA_DIR = dataset_path
if os.path.exists(os.path.join(dataset_path, "data")):
    DATA_DIR = os.path.join(dataset_path, "data")

os.makedirs('models', exist_ok=True)

# ==========================================
# 2. IMPORTS & HYPERPARAMETERS
# ==========================================
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import GlobalAveragePooling2D, Dropout, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt

# Hyperparameters
BATCH_SIZE = 32
IMAGE_SIZE = (224, 224)
INITIAL_EPOCHS = 15
FINE_TUNE_EPOCHS = 15
MODEL_SAVE_PATH = "models/plant_disease_model.keras"

# ==========================================
# 3. DATA AUGMENTATION (Crucial for Low Loss)
# ==========================================
# Aggressive augmentation for training to prevent overfitting
train_datagen = ImageDataGenerator(
    preprocessing_function=tf.keras.applications.efficientnet.preprocess_input,
    rotation_range=30,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode="nearest",
    validation_split=0.2 # Reserve 20% of data for validation
)

print("\nLoading Training Data...")
train_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training"
)

print("Loading Validation Data...")
val_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation"
)

# Save class labels to match exactly what the model learned
classes = list(train_generator.class_indices.keys())
with open("models/labels.txt", "w") as f:
    for c in classes:
        f.write(c + "\n")
print(f"Discovered classes: {classes}")

# ==========================================
# 4. BUILD THE MODEL ARCHITECTURE
# ==========================================
# Load EfficientNetB0 without the top classification layer
base_model = EfficientNetB0(weights="imagenet", include_top=False, input_shape=(224, 224, 3))

# Freeze the base model to prevent destroying pre-trained weights
base_model.trainable = False

# Build the new custom classification head
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)  # 50% Dropout to prevent overfitting
outputs = Dense(len(classes), activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=outputs)
model.compile(optimizer=Adam(learning_rate=1e-3), loss="categorical_crossentropy", metrics=["accuracy"])

# ==========================================
# 5. CALLBACKS
# ==========================================
callbacks = [
    ModelCheckpoint(MODEL_SAVE_PATH, monitor='val_loss', save_best_only=True, verbose=1),
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6, verbose=1)
]

# ==========================================
# 6. PHASE 1: TRAIN THE HEAD
# ==========================================
print("\n--- PHASE 1: Training the Custom Head ---")
history_phase1 = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=INITIAL_EPOCHS,
    callbacks=callbacks
)

# ==========================================
# 7. PHASE 2: FINE-TUNING
# ==========================================
print("\n--- PHASE 2: Fine-Tuning Deeper Layers ---")
# Unfreeze the base model
base_model.trainable = True

# Freeze the bottom 100 layers, leaving the top layers to fine-tune
for layer in base_model.layers[:100]:
    layer.trainable = False

# Recompile with a drastically lower learning rate
model.compile(optimizer=Adam(learning_rate=1e-5), loss="categorical_crossentropy", metrics=["accuracy"])

history_phase2 = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=FINE_TUNE_EPOCHS,
    callbacks=callbacks
)

# ==========================================
# 8. PLOT RESULTS
# ==========================================
acc = history_phase1.history['accuracy'] + history_phase2.history['accuracy']
val_acc = history_phase1.history['val_accuracy'] + history_phase2.history['val_accuracy']
loss = history_phase1.history['loss'] + history_phase2.history['loss']
val_loss = history_phase1.history['val_loss'] + history_phase2.history['val_loss']

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.axvline(x=INITIAL_EPOCHS-1, color='r', linestyle='--', label='Fine-Tuning Starts')
plt.legend()
plt.title('Accuracy')

plt.subplot(1, 2, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.axvline(x=INITIAL_EPOCHS-1, color='r', linestyle='--', label='Fine-Tuning Starts')
plt.legend()
plt.title('Loss')
plt.show()

print(f"\nTraining Complete! Download '{MODEL_SAVE_PATH}' and 'models/labels.txt' from the file explorer.")

