from fpdf import FPDF
import tempfile
import datetime

def safe_txt(text):
    if not text: return "N/A"
    return str(text).encode('latin-1', 'replace').decode('latin-1')

def create_pdf_report(predicted_class, confidence, plan, image):
    pdf = FPDF()
    pdf.add_page()
    
    # 1. Title Banner
    pdf.set_fill_color(34, 197, 94) # Nice green
    pdf.rect(0, 0, 210, 25, 'F')
    
    pdf.set_y(8)
    pdf.set_font("Arial", 'B', 22)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, txt="Corn Doctor Pro - Diagnostics", ln=True, align='C')
    
    # 2. Date and Subheader
    pdf.set_y(35)
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(31, 41, 55) # Dark gray slate
    disease_name = plan.get('name', predicted_class)
    pdf.cell(120, 8, txt=safe_txt(f"Diagnosis: {disease_name}"), ln=False)
    
    pdf.set_font("Arial", 'I', 11)
    pdf.set_text_color(107, 114, 128) # Lighter gray
    pdf.cell(70, 8, txt=f"Date: {datetime.datetime.now().strftime('%b %d, %Y')}", ln=True, align='R')
    
    # 3. Quick Stats (Pathogen & Confidence) & Image
    current_y = pdf.get_y()
    
    pdf.set_font("Arial", 'B', 11)
    pdf.set_text_color(75, 85, 99)
    pdf.cell(120, 6, txt=safe_txt(f"Pathogen: {plan.get('scientific_name', 'N/A')}"), ln=True)
    pdf.cell(120, 6, txt=f"AI Confidence: {confidence:.1f}%", ln=True)
    
    if image:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as tmp:
            if image.mode in ('RGBA', 'P'): image = image.convert('RGB')
            # maintain aspect ratio, resize thumbnail to look great
            image.thumbnail((300, 300))
            image.save(tmp.name)
            # place image on the right
            pdf.image(tmp.name, x=135, y=current_y, w=60)
            
    # Draw a subtle separator line
    highest_y = max(pdf.get_y(), current_y + 40)
    pdf.set_y(highest_y + 5)
    pdf.set_draw_color(229, 231, 235)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    def add_section(title, content, color):
        if not content or content == "N/A": return
        pdf.set_font("Arial", 'B', 13)
        pdf.set_text_color(*color)
        pdf.cell(0, 8, txt=title, ln=True)
        
        pdf.set_font("Arial", '', 11)
        pdf.set_text_color(55, 65, 81)
        
        # Clean up any potential markdown bullet points from the AI to look neat
        lines = []
        for line in safe_txt(content).split('\n'):
            line = line.strip()
            if line:
                if line.startswith('* ') or line.startswith('- '):
                    lines.append(chr(149) + " " + line[2:])
                else:
                    lines.append(line)
        
        pdf.multi_cell(0, 6, txt="\n".join(lines))
        pdf.ln(4)

    # 4. Content Sections with color coding
    add_section("Key Symptoms:", plan.get('symptoms', 'N/A'), (220, 38, 38)) # Reddish
    add_section("Preventative Practices:", plan.get('prevention', 'N/A'), (37, 99, 235)) # Blue
    add_section("Organic Controls:", plan.get('organic', 'N/A'), (22, 163, 74)) # Green
    add_section("Chemical Controls:", plan.get('chemical', 'N/A'), (217, 119, 6)) # Orange
    
    # 5. Footer
    pdf.set_y(-30)
    pdf.set_draw_color(229, 231, 235)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    pdf.set_font("Arial", 'B', 10)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(0, 5, txt="Karan Kumawat - Founder & Chairman", ln=True, align='C')
    pdf.set_font("Arial", 'I', 9)
    pdf.cell(0, 5, txt="Generated by Corn Doctor AI Diagnostics", ln=True, align='C')

    return pdf.output(dest='S').encode('latin-1')